/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_MI2A_AndreMahesaPutra;

import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class HalamanTransfer extends javax.swing.JFrame {

    /**
     * Creates new form HalamanTransfer
     */
    saldoModel saldo;
    
    public HalamanTransfer() {
        initComponents();
        txtGagal.setVisible(false);
        saldo=new saldoModel();
        txtSaldo.setText("Jumlah Saldo Rp"+saldo.getSaldo());
        panelBerhasil.setVisible(false);
        
    }

    public JTextField getTxtTransfer() {
        return txtTransfer;
    }

    public JTextField getTxtRekening() {
        return txtRekening;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelBerhasil = new javax.swing.JPanel();
        txt = new javax.swing.JLabel();
        txtSisa = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnLanjut = new javax.swing.JButton();
        txtRek = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTampilTransfer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGagal = new javax.swing.JLabel();
        txtRekening = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        txtSaldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOke1 = new javax.swing.JButton();
        txtTransfer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(0, 153, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel2.setLayout(null);

        panelBerhasil.setBackground(new java.awt.Color(0, 102, 255));
        panelBerhasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBerhasil.setLayout(null);

        txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(0, 255, 0));
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText("TRANFER BERHASIL");
        panelBerhasil.add(txt);
        txt.setBounds(20, 30, 420, 50);

        txtSisa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSisa.setForeground(new java.awt.Color(255, 255, 255));
        txtSisa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSisa.setText("Sisa Saldo");
        panelBerhasil.add(txtSisa);
        txtSisa.setBounds(10, 220, 460, 60);

        btnCancel.setBackground(new java.awt.Color(0, 153, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("KEMBALI");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelBerhasil.add(btnCancel);
        btnCancel.setBounds(30, 340, 190, 70);

        btnLanjut.setBackground(new java.awt.Color(0, 153, 255));
        btnLanjut.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLanjut.setForeground(new java.awt.Color(255, 255, 255));
        btnLanjut.setText("LANJUTKAN");
        btnLanjut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        panelBerhasil.add(btnLanjut);
        btnLanjut.setBounds(260, 340, 190, 70);

        txtRek.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRek.setForeground(new java.awt.Color(255, 255, 255));
        txtRek.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRek.setText("No Rekening");
        panelBerhasil.add(txtRek);
        txtRek.setBounds(10, 100, 460, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No Rekening");
        panelBerhasil.add(jLabel9);
        jLabel9.setBounds(10, 100, 460, 60);

        txtTampilTransfer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTampilTransfer.setForeground(new java.awt.Color(255, 255, 255));
        txtTampilTransfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTampilTransfer.setText("Jumlah Transfer");
        panelBerhasil.add(txtTampilTransfer);
        txtTampilTransfer.setBounds(10, 160, 460, 60);

        jPanel2.add(panelBerhasil);
        panelBerhasil.setBounds(300, 80, 480, 440);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jumlah Transfer");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 240, 340, 60);

        txtGagal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtGagal.setForeground(new java.awt.Color(204, 0, 0));
        txtGagal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGagal.setText("SALDO ANDA TIDAK CUKUP");
        jPanel2.add(txtGagal);
        txtGagal.setBounds(310, 430, 420, 50);

        txtRekening.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(txtRekening);
        txtRekening.setBounds(310, 330, 430, 60);

        btnKembali.setBackground(new java.awt.Color(0, 153, 255));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("KEMBALI");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali);
        btnKembali.setBounds(20, 20, 190, 70);

        txtSaldo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaldo.setText("Jumlah Saldo Rp");
        jPanel2.add(txtSaldo);
        txtSaldo.setBounds(80, 180, 430, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TRANFER SALDO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(330, 100, 420, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rekening Tujuan");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 330, 340, 60);

        btnOke1.setBackground(new java.awt.Color(0, 153, 255));
        btnOke1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnOke1.setForeground(new java.awt.Color(255, 255, 255));
        btnOke1.setText("OKE");
        btnOke1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOke1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOke1);
        btnOke1.setBounds(430, 520, 190, 70);

        txtTransfer.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel2.add(txtTransfer);
        txtTransfer.setBounds(310, 240, 430, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1024, 600);

        setBounds(0, 0, 1046, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOke1ActionPerformed
        // TODO add your handling code here:
        saldo=new saldoModel();
        saldo.setTransfer(this.getTxtTransfer().getText());
        saldo.setRekening(this.getTxtRekening().getText());
        if(saldo.getSaldo()>saldo.getTransfer()){
            saldo.prosesTransfer();
            panelBerhasil.setVisible(true);
            txtRek.setText("No Rekening : "+saldo.getRekening());
            txtTampilTransfer.setText("Jumlah Transfer : Rp."+saldo.getTransfer());
            txtSisa.setText("Sisa Saldo : Rp."+saldo.getSaldo());
        }else{
            txtGagal.setVisible(true);
        }
    }//GEN-LAST:event_btnOke1ActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        panelBerhasil.setVisible(false);
        this.setVisible(true);
        txtTransfer.setText("");
        txtRekening.setText("");
        txtSaldo.setText("Jumlah Saldo Rp"+saldo.getSaldo());
    }//GEN-LAST:event_btnLanjutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnOke1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBerhasil;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txtGagal;
    private javax.swing.JLabel txtRek;
    private javax.swing.JTextField txtRekening;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtSisa;
    private javax.swing.JLabel txtTampilTransfer;
    private javax.swing.JTextField txtTransfer;
    // End of variables declaration//GEN-END:variables
}
