/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UTS_MI2A_AndreMahesaPutra;

/**
 *
 * @author user
 */
public class HalamanSetor extends javax.swing.JFrame {

    /**
     * Creates new form HalamanSetor
     */
    setorModel setor;
    public HalamanSetor() {
        initComponents();
        panel2.setVisible(false);
        setor=new setorModel();
        txtSetoran.setVisible(false);
        txtPecahan.setVisible(false);
        txtSaldoAwal.setText("JUMLAH SALDO Rp."+setor.getSaldo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        btnKembali1 = new javax.swing.JButton();
        saldo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        txtSaldoAwal = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn50 = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSetoran = new javax.swing.JLabel();
        btnLanjut = new javax.swing.JButton();
        txtPecahan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 153, 255));
        panel2.setLayout(null);

        btnKembali1.setBackground(new java.awt.Color(0, 153, 255));
        btnKembali1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKembali1.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali1.setText("KEMBALI KE HALAMAN UTAMA");
        btnKembali1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        panel2.add(btnKembali1);
        btnKembali1.setBounds(390, 460, 280, 70);

        saldo.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        saldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldo.setText("Rp.");
        panel2.add(saldo);
        saldo.setBounds(160, 270, 700, 58);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SETORAN TUNAI BERHASIL");
        panel2.add(jLabel7);
        jLabel7.setBounds(180, 70, 700, 58);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SALDO ANDA");
        panel2.add(jLabel8);
        jLabel8.setBounds(160, 180, 700, 58);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 1020, 610);

        panel1.setBackground(new java.awt.Color(0, 153, 255));
        panel1.setLayout(null);

        txtSaldoAwal.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        txtSaldoAwal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSaldoAwal.setText("JUMLAH SALDO Rp.");
        panel1.add(txtSaldoAwal);
        txtSaldoAwal.setBounds(200, 280, 660, 34);

        btn100.setBackground(new java.awt.Color(0, 153, 255));
        btn100.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("Rp100.000");
        btn100.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        panel1.add(btn100);
        btn100.setBounds(670, 200, 270, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SETORAN TUNAI");
        panel1.add(jLabel4);
        jLabel4.setBounds(200, 20, 600, 58);

        btn50.setBackground(new java.awt.Color(0, 153, 255));
        btn50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn50.setForeground(new java.awt.Color(255, 255, 255));
        btn50.setText("Rp50.000");
        btn50.setToolTipText("");
        btn50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });
        panel1.add(btn50);
        btn50.setBounds(110, 200, 270, 70);

        btnKembali.setBackground(new java.awt.Color(0, 153, 255));
        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("KEMBALI");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        panel1.add(btnKembali);
        btnKembali.setBounds(250, 420, 250, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PILIH PECAHAN UANG :");
        panel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 390, 34);

        txtSetoran.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        txtSetoran.setForeground(new java.awt.Color(51, 255, 0));
        txtSetoran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSetoran.setText("TEKAN (LANJUT) SETORAN Rp.");
        panel1.add(txtSetoran);
        txtSetoran.setBounds(200, 360, 720, 34);

        btnLanjut.setBackground(new java.awt.Color(0, 153, 255));
        btnLanjut.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLanjut.setForeground(new java.awt.Color(255, 255, 255));
        btnLanjut.setText("LANJUT");
        btnLanjut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        panel1.add(btnLanjut);
        btnLanjut.setBounds(590, 420, 250, 70);

        txtPecahan.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        txtPecahan.setForeground(new java.awt.Color(51, 255, 0));
        txtPecahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPecahan.setText("PECAHAN");
        panel1.add(txtPecahan);
        txtPecahan.setBounds(200, 320, 720, 34);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1024, 600);

        setBounds(0, 0, 1046, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
        setor=new setorModel();
        txtSetoran.setVisible(true);
        txtPecahan.setVisible(true);
        txtPecahan.setText("PECAHAN Rp."+100000);
        txtSetoran.setText("TEKAN (LANJUT) SETORAN Rp."+setor.getSetor());
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        // TODO add your handling code here:
        setor=new setorModel();
        txtSetoran.setVisible(true);
        txtPecahan.setVisible(true);
        txtPecahan.setText("PECAHAN Rp."+50000);
        txtSetoran.setText("TEKAN (LANJUT) SETORAN Rp."+setor.getSetor());
    }//GEN-LAST:event_btn50ActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        setor=new setorModel();
        panel1.setVisible(false);
        panel2.setVisible(true);
        saldo.setText("Rp."+setor.saldoTambah(setor.getSetor()));
    }//GEN-LAST:event_btnLanjutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanSetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel txtPecahan;
    private javax.swing.JLabel txtSaldoAwal;
    private javax.swing.JLabel txtSetoran;
    // End of variables declaration//GEN-END:variables
}
